apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: 'mywebsite-staticip'
  labels:
    app: mywebsite
spec:
  backend:
    serviceName: mywebsite-service
    servicePort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: mywebsite-service
spec:
  selector:
    app: mywebsite
  type:  NodePort
  # expose ports
  ports:
  - port: 80
    targetPort: 80